spring:
  application:
    name: AppProdutos2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5433/appprodutos2_db
    username: postgres
    password: admin